(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$$('[data-part]').forEach(b=>b.addEventListener('click',()=>{$$('[data-part]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$$('[data-marker]').forEach(x=>x.classList.toggle('active',x.dataset.marker===b.dataset.part));$('.anatomy').scrollIntoView({block:'nearest',behavior:'auto'});}));
let divisionTimer=null,clockTimer=null;
const descriptions=['One parent cell carries its chromosome in the nucleoid region.','The chromosome is copied while the cell grows. The two DNA copies move apart.','A dividing wall called a septum forms between the separated DNA copies.','The cell separates into two daughter cells, each with a chromosome copy.'];
function stage(n){$('.fission-drawing').dataset.stage=n;$('.fission-drawing').setAttribute('aria-label',descriptions[n]);$('#fission-description').textContent=descriptions[n];$$('[data-stage-button]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.stageButton===n)));}
function stopDivision(){clearInterval(divisionTimer);divisionTimer=null;if($('#fission-play'))$('#fission-play').textContent='Animate division';}
$$('[data-stage-button]').forEach(b=>b.addEventListener('click',()=>{stopDivision();stage(+b.dataset.stageButton);}));
$('#fission-play')?.addEventListener('click',()=>{if(divisionTimer){stopDivision();return;}let n=0;stage(0);$('#fission-play').textContent='Pause division';divisionTimer=setInterval(()=>{stage(++n);if(n===3)stopDivision();},1400);});
const control=$('[data-clock]');
function stopClock(){clearInterval(clockTimer);clockTimer=null;if(control)control.querySelector('[data-play]').textContent='Play 24 hours';}
function short(n){let v=Number(n);for(const [d,u]of [[1e21,'sextillion'],[1e18,'quintillion'],[1e15,'quadrillion'],[1e12,'trillion'],[1e9,'billion'],[1e6,'million']])if(v>=d)return (v/d).toLocaleString('en-US',{maximumFractionDigits:2})+' '+u;return n.toLocaleString('en-US');}
function growth(n){const canvas=$('#growth-canvas');if(!canvas)return;const ctx=canvas.getContext('2d'),count=Math.min(256,2**n);ctx.clearRect(0,0,1000,430);for(let i=0;i<count;i++){const col=i%16,row=Math.floor(i/16);const x=42+col*60,y=25+row*25;ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(i*4)*.3);ctx.fillStyle=i%5===0?'#ffd28a':'#87e9d4';ctx.beginPath();ctx.roundRect(-17,-6,34,12,6);ctx.fill();ctx.strokeStyle='#224b55';ctx.beginPath();ctx.moveTo(-8,0);ctx.lineTo(8,0);ctx.stroke();ctx.restore();}const txt=n<=8?'Each drawn cell represents one bacterium.':'Representative sample: 256 drawn cells. The population is now too large to show every cell.';$('[data-sample]').textContent=txt;canvas.setAttribute('aria-label',short(2n**BigInt(n))+' bacteria. '+txt);}
function scale(n){if(!$('#scale-svg'))return;const edge=Math.cbrt(15*2**n),earth=edge>=5e6,car=edge<50,ref=earth?12756000:car?5:edge<5000?100:100000;const max=Math.max(edge,ref),factor=280/max;const size=edge*factor,refsize=ref*factor;$('#cube-edge').textContent=edge>=1609.344?(edge/1609.344).toLocaleString('en-US',{maximumFractionDigits:1})+' miles':edge.toLocaleString('en-US',{maximumFractionDigits:2})+' m';for(const id of ['cube-face','cube-texture']){const r=$('#'+id);r.setAttribute('width',size);r.setAttribute('height',size);r.setAttribute('x',280-size/2);r.setAttribute('y',385-size);}const x=280-size/2,y=385-size,d=size*.14;$('#cube-top').setAttribute('d',`M${x} ${y}l${d} ${-d}h${size}l${-d} ${d}z`);$('#cube-side').setAttribute('d',`M${x+size} ${y}l${d} ${-d}v${size}l${-d} ${d}z`);$('#reference-earth').style.display=earth?'':'none';$('#reference-car').style.display=car?'':'none';$('#reference-bar').style.display=!earth&&!car?'':'none';if(earth){$('#earth-disc').setAttribute('r',refsize/2);$('#earth-disc').setAttribute('cy',385-refsize/2);$('#earth-land').setAttribute('transform',`translate(${740-740*refsize/180} ${385-refsize/2-280*refsize/180}) scale(${refsize/180})`);}if(car)$('#reference-car').setAttribute('transform',`translate(${740-725*refsize/151} ${385-383*refsize/151}) scale(${refsize/151})`);$('#reference-bar').setAttribute('height',refsize);$('#reference-bar').setAttribute('y',385-refsize);$('#reference-label').textContent=earth?'Earth · 7,926 miles diameter':car?'Car · 5 m length':ref===100?'100 m reference height':'62.1 miles reference height';$('#scale-desc').textContent=`${short(2n**BigInt(n))} car-sized cells fill an equivalent cube with edge ${$('#cube-edge').textContent}. Cube edge and reference length use the same scale. Camera zooms out automatically.`;}
function render(){const n=+control.querySelector('input').value;$('[data-count]').textContent=short(2n**BigInt(n));if($('[data-generation]'))$('[data-generation]').textContent=n;if($('[data-exact]'))$('[data-exact]').textContent=(2n**BigInt(n)).toLocaleString('en-US');const mins=n*20;control.querySelector('output').textContent=Math.floor(mins/60)+' h '+String(mins%60).padStart(2,'0')+' min';control.querySelector('input').setAttribute('aria-valuetext',Math.floor(mins/60)+' hours '+mins%60+' minutes');growth(n);scale(n);}
if(control){const slider=control.querySelector('input');slider.addEventListener('input',()=>{stopClock();render();});control.querySelector('[data-reset]').addEventListener('click',()=>{stopClock();slider.value=0;render();});control.querySelector('[data-play]').addEventListener('click',()=>{if(clockTimer){stopClock();return;}if(+slider.value===72)slider.value=0;render();control.querySelector('[data-play]').textContent='Pause';clockTimer=setInterval(()=>{slider.value=+slider.value+1;render();if(+slider.value===72)stopClock();},300);});render();}
function motion(){const paused=document.body.classList.contains('paused');if(paused){stopDivision();stopClock();}for(const b of [$('#fission-play'),$('[data-play]')])if(b)b.disabled=paused;if($('[data-motion-note]'))$('[data-motion-note]').textContent=paused?'Motion paused. Use the slider, or select Resume motion in the header.':'Animation compresses 24 hours into about 22 seconds. You can also drag the time slider.';}
new MutationObserver(motion).observe(document.body,{attributes:true,attributeFilter:['class']});motion();document.addEventListener('visibilitychange',()=>{if(document.hidden){stopClock();stopDivision();}});
})();
